# This file was generated by @liquid-labs/catalyst-builder-node. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-builder-node for further details

#####
# build dist/sdlc-projects-badges-coverage.js
#####

CATALYST_CATALYST_BUILDER_BADGE_COVERAGE_JS:=$(DIST)/sdlc-projects-badges-coverage.js
CATALYST_CATALYST_BUILDER_BADGE_COVERAGE_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(CATALYST_CATALYST_BUILDER_BADGE_COVERAGE_JS)

$(CATALYST_CATALYST_BUILDER_BADGE_COVERAGE_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_CATALYST_BUILDER_BADGE_COVERAGE_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/sdlc-projects-badges-coverage.js
#####
